#spring config
spring:
  config:
    activate:
      on-profile: stage
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    hikari:
      auto-commit: false
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 2000000
      pool-name: hikari-cp-sboot-koscotms-stage
      read-only: false
      minimum-idle: 3
      connection-init-sql: SELECT 1 FROM DUAL
      # driver-class-name: oracle.jdbc.driver.OracleDriver
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      # jdbc-url: jdbc:oracle:thin:@192.1.1.46:1521:IODB
      jdbc-url: jdbc:p6spy:oracle:thin:@192.1.1.46:1521:IODB
      username: ENC(42zMsgwatGgXaxGOf5rp2T/+niUSBxCy)
      password: ENC(SSpuqePDK1HJ8lBNElHkWXF0qY2Kqby0)
      #      username: TMSDBO
      #      password: DBOTMS
#  profiles:
#    active: stage

#server config
server:
  port: 28083
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: /var/_was_file_and_logs/server/_files

file:
  upload:
    base-path-upload: /var/_was_file_and_logs/server/_files

logging:
  file:
    path:  /var/_was_file_and_logs/server/_logs
  config: classpath:logback/logback-${spring.profiles.active}.xml
  level:
    com:
      zaxxer:
        hikari: debug
    root: debug
    p6spy: debug
    web: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true

debug: true

api:
  key:
    tmap: NTNGGnkhup6wmk7knqIaJ8QSBxxItOcH4EO5Ny7p
    url-short-naver-client-id: uHdHK2Gs0TSx1GT0Ait0
    url-short-naver-client-secret: vAGSJugg5E
    url-short-naver-url: https://openapi.naver.com/v1/util/shorturl?url=

fcm:
  scheduler:
    enable: true

bus:
  scheduler:
    enable: true