#spring config
spring:
  config:
    activate:
      on-profile: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    hikari:
      auto-commit: false
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 2000000
      pool-name: hikari-cp-sboot-koscotms-local
      read-only: false
      minimum-idle: 3
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      jdbc-url: jdbc:p6spy:mysql://192.192.158.73:3306/vue?allowPublicKeyRetrieval=true&useSSL=false
      username: vue
      password: 2025*Kiwoom
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: true
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    open-in-view: false

#server config
server:
  port: 7080
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 500MB
      location: ./upload

file:
  upload:
    base-path-upload: ./upload

logging:
  file:
    path: ./_log_dir
  config: classpath:logback/logback-${spring.profiles.active}.xml
  level:
    com.p6spy: debug
    p6spy: debug
    kr.co.dysnt.framework.core.config.formatter: debug
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql: off
    web: debug
    kr.co.dysnt: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      enable-format: true
      slow-sql-millis: 1000
      stack-trace-logging: false
      deregistery-drivers: false
      format-sql: true
      log-file: spy.log
      append: true
      exclude-categories: info,debug,result,batch,commit,rollback
      date-format: yyyy-MM-dd HH:mm:ss
      use-native-parser: false
      log-format: "%(currentTime) | %(executionTime)ms | %(category) | %(sql)"

debug: true

api:
  key:
    tmap: NTNGGnkhup6wmk7knqIaJ8QSBxxItOcH4EO5Ny7p
    url-short-naver-client-id: uHdHK2Gs0TSx1GT0Ait0
    url-short-naver-client-secret: vAGSJugg5E
    url-short-naver-url: https://openapi.naver.com/v1/util/shorturl?url=

fcm:
  scheduler:
    enable: false

bus:
  scheduler:
    enable: false
