#spring config
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    hikari:
      auto-commit: false
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 2000000
      pool-name: hikari-cp-sboot-koscotms-dev
      read-only: false
      minimum-idle: 3
      connection-init-sql: SELECT 1 FROM DUAL
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      jdbc-url: jdbc:p6spy:oracle:thin:@192.168.1.15:1521:koscotest
      username: WSSDBO
      password: WSSDBO
  devtools:
    livereload:
      enabled: true

#server config
server:
  port: 8080
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      location: /home/dysnt/tomcat/wss-front/_was_file_and_logs/_files

file:
  upload:
    base-path-upload: /home/dysnt/tomcat/wss-front/_was_file_and_logs/_files

logging:
  file:
    path: /home/dysnt/tomcat/wss-front/_was_file_and_logs/_logs
  config: classpath:logback/logback-${spring.profiles.active}.xml
  level:
    com:
      zaxxer:
        hikari: debug
    root: debug
    p6spy: debug
    web: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true

debug: true

api:
  key:
    tmap: NTNGGnkhup6wmk7knqIaJ8QSBxxItOcH4EO5Ny7p
    url-short-naver-client-id: uHdHK2Gs0TSx1GT0Ait0
    url-short-naver-client-secret: vAGSJugg5E
    url-short-naver-url: https://openapi.naver.com/v1/util/shorturl?url=

fcm:
  scheduler:
    enable: false

bus:
  scheduler:
    enable: false